# This is a basic workflow to help you get started with Actions

name: Website CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build Next.JS
        run: yarn build
        
      - name: Run E2E Tests
        run: yarn e2e:headless
